function rot_mat = y_x_rot(beta,alpha,gamma,order)
gamma=gamma*pi/180;
alpha=alpha*pi/180;
beta=beta*pi/180;
rot(:,:,1) = [     1     ,      0      ,      0     ;...
                   0     ,   cos(beta) ,  -sin(beta);...
                   0     ,   sin(beta) ,  cos(beta)];
rot(:,:,2) = [cos(alpha) ,      0      ,  sin(alpha);...
                   0     ,      1      ,      0     ;...
              -sin(alpha),      0      , cos(alpha)];
rot(:,:,3) = [ cos(gamma), -sin(gamma) ,      0     ;...
               sin(gamma), cos(gamma)  ,      0     ;...
                   0     ,      0      ,      1    ];
rot_mat = eye(3,3);
for i = 1:3
    rotation = rot(:,:,find(order==i));
    rot_mat = rotation*rot_mat;
end